### ISSUE TITLE
Update proposal

### ISSUE THREAD

**Issue by jonalf** [JasonWu00/final-project#1]
Your proposal mentions there may be significant changes. You should have a more secure sense of the design than that. Changes are going to happen, but your design should start off on more sound footing. Also, as mentioned in class, your proposal mentions using IPC concepts in a network program, which will not work.

**Comment by JasonWu00** [comment]
Proposal updated to remove IPC from the list of concepts to implement. The proposal has been revised to include less uncertainty on topics such as networking and to lay down a more concrete set of information regarding the expected final product.

**Comment by jonalf** [comment]
approved

make it so
